# # Builder
FROM node:10.16-alpine AS builder
WORKDIR /app
# needed by babel
RUN apk add --update \
  python \
  python-dev \
  build-base \
  make

COPY package.json .
COPY yarn.lock .
ARG npm_token
RUN echo "//registry.npmjs.org/:_authToken=$npm_token" > .npmrc
RUN yarn install --frozen-lockfile

COPY . .

ARG stage
ENV STAGE=$stage
RUN yarn generate:views
RUN yarn build:server
