# This is the Dockerfile for building a development image with Pizzly

# Build image 
FROM node:14-alpine

# Install make to run tests
# Make sure we have ca certs for TLS
RUN apk add --no-cache ca-certificates make=4.3-r0

WORKDIR /app

# Copy in dependencies for building
COPY . ./

RUN yarn install --frozen-lockfile

RUN yarn build

CMD ["node", "./dist/src/index.js"]
