// Generated by ts-to-zod
// eslint-disable-next-line import/no-extraneous-dependencies
import { z } from 'zod';

export const salesforceAccountSchema = z.object({
    id: z.string(),
    name: z.string(),
    website: z.string(),
    description: z.string(),
    no_employees: z.number(),
    last_modified_date: z.string()
});

export const salesforceContactSchema = z.object({
    id: z.string(),
    first_name: z.string(),
    last_name: z.string(),
    email: z.string(),
    account_id: z.string(),
    last_modified_date: z.string()
});

export const salesforceDealSchema = z.object({
    id: z.string(),
    name: z.string(),
    amount: z.number(),
    stage: z.string(),
    account_id: z.string(),
    last_modified_date: z.string()
});

export const salesforceArticleSchema = z.object({
    id: z.string(),
    title: z.string(),
    content: z.string(),
    last_modified_date: z.string()
});

export const salesforceTicketSchema = z.object({
    id: z.string(),
    case_number: z.string(),
    subject: z.string().nullable(),
    account_id: z.string(),
    account_name: z.string().nullable(),
    contact_id: z.string(),
    contact_name: z.string().nullable(),
    owner_id: z.string(),
    owner_name: z.string().nullable(),
    priority: z.string(),
    status: z.string(),
    description: z.string().nullable(),
    type: z.string(),
    created_date: z.string(),
    closed_date: z.string(),
    origin: z.string(),
    is_closed: z.boolean(),
    is_escalated: z.boolean(),
    conversation: z.object({
        id: z.string(),
        body: z.string(),
        created_date: z.string(),
        created_by: z.string()
    }),
    last_modified_date: z.string()
});

export const salesforceEntitySchema = z.object({
    name: z.string()
});

export const fieldSchema = z.object({
    name: z.string(),
    label: z.string(),
    type: z.string(),
    referenceTo: z.array(z.string()),
    relationshipName: z.string().nullable()
});

export const nestedFieldSchemaSchema = z.object({
    fields: z.array(fieldSchema)
});

export const childFieldSchema = z.object({
    object: z.string(),
    relationshipName: z.string().nullable(),
    field: z.string()
});

export const salesforceFieldSchemaSchema = z.object({
    fields: z.array(fieldSchema),
    childRelationships: z.array(childFieldSchema)
});

export const actionResponseErrorDetailsSchema = z.object({
    message: z.string(),
    method: z.string(),
    url: z.string(),
    code: z.string()
});

export const actionResponseErrorSchema = z.object({
    message: z.string(),
    details: actionResponseErrorDetailsSchema.optional()
});
