version: '3.9'
services:
    nango-db:
        image: postgres:15.5-alpine
        container_name: nango-db
        environment:
            POSTGRES_PASSWORD: nango
            POSTGRES_USER: nango
            POSTGRES_DB: nango
        ports:
            - '${NANGO_DB_PORT:-5432}:5432'
        volumes:
            - ./nango-data:/var/lib/postgresql/data
        networks:
            - nango

    nango-redis:
        image: redis:7.2.4
        container_name: nango-redis
        ports:
            - '6379:6379'
        networks:
            - nango

    elasticsearch:
        container_name: elasticsearch
        image: elasticsearch:8.13.0
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - elasticsearch-data1:/usr/share/elasticsearch/data
        ports:
            - 9500:9200
            - 9600:9300
        environment:
            - discovery.type=single-node
            - xpack.security.enabled=false
        networks:
            - nango
        deploy:
            resources:
                limits:
                    memory: 2GB

    activemq:
        container_name: activemq
        image: apache/activemq-classic:5.18.3
        ports:
            - '8161:8161' # Web console
            - '61613:61613' # STOMP
            - '61614:61614' # WS
        networks:
            - nango

networks:
    nango:

volumes:
    elasticsearch-data1:
        driver: local
