import type { PlanDefinition } from '@nangohq/types';

export const freePlanFlags: PlanDefinition['flags'] = {
    api_rate_limit_size: 'm',
    environments_max: 2,
    has_otel: false,
    has_sync_variants: false,
    connections_max: 10,
    records_max: 100_000,
    proxy_max: 100_000,
    function_executions_max: 100_000,
    function_compute_gbms_max: 50_000_000,
    webhook_forwards_max: 100_000,
    function_logs_max: 100_000,
    sync_frequency_secs_min: 3600,
    auto_idle: true,
    monthly_actions_max: 1000,
    monthly_active_records_max: 5000,
    has_webhooks_script: false,
    has_webhooks_forward: false,
    can_override_docs_connect_url: false,
    can_customize_connect_ui_theme: false,
    can_disable_connect_ui_watermark: false
};

export const starterPlanFlags: PlanDefinition['flags'] = {
    api_rate_limit_size: 'l',
    environments_max: 3,
    has_otel: false,
    has_sync_variants: false,
    sync_frequency_secs_min: 3600,
    connections_max: null,
    records_max: null,
    proxy_max: null,
    function_executions_max: null,
    function_compute_gbms_max: null,
    webhook_forwards_max: null,
    function_logs_max: null,
    auto_idle: false,
    monthly_actions_max: null,
    monthly_active_records_max: null,
    trial_start_at: null,
    trial_end_at: null,
    trial_end_notified_at: null,
    trial_extension_count: 0,
    trial_expired: null,
    has_webhooks_script: false,
    has_webhooks_forward: false,
    can_override_docs_connect_url: false,
    can_customize_connect_ui_theme: false,
    can_disable_connect_ui_watermark: false
};

export const growthPlanFlags: PlanDefinition['flags'] = {
    api_rate_limit_size: 'l',
    environments_max: 10,
    has_otel: true,
    has_sync_variants: true,
    sync_frequency_secs_min: 30,
    auto_idle: false,
    connections_max: null,
    records_max: null,
    proxy_max: null,
    function_executions_max: null,
    function_compute_gbms_max: null,
    webhook_forwards_max: null,
    function_logs_max: null,
    monthly_actions_max: null,
    monthly_active_records_max: null,
    trial_start_at: null,
    trial_end_at: null,
    trial_end_notified_at: null,
    trial_extension_count: 0,
    trial_expired: null,
    has_webhooks_script: true,
    has_webhooks_forward: true,
    can_override_docs_connect_url: false,
    can_customize_connect_ui_theme: true,
    can_disable_connect_ui_watermark: true
};

export const enterprisePlanFlags: PlanDefinition['flags'] = {
    api_rate_limit_size: '2xl',
    environments_max: 10,
    has_otel: true,
    has_sync_variants: true,
    sync_frequency_secs_min: 30,
    connections_max: null,
    records_max: null,
    proxy_max: null,
    function_executions_max: null,
    function_compute_gbms_max: null,
    webhook_forwards_max: null,
    function_logs_max: null,
    auto_idle: false,
    monthly_actions_max: null,
    monthly_active_records_max: null,
    trial_start_at: null,
    trial_end_at: null,
    trial_end_notified_at: null,
    trial_extension_count: 0,
    trial_expired: null,
    has_webhooks_script: true,
    has_webhooks_forward: true,
    can_override_docs_connect_url: false,
    can_customize_connect_ui_theme: true,
    can_disable_connect_ui_watermark: true
};
