import type { PlanDefinition } from '@nangohq/types';

/**
 * Latest plans
 */

export const freeV2Plan: PlanDefinition = {
    code: 'free-v2',
    orbId: 'free',
    orbVersion: 2,
    title: 'Free',
    description: 'For hobby and testing.',
    isPaid: false,
    prevPlan: null,
    nextPlan: ['starter-v2', 'growth-v2'],
    canChange: true,
    basePrice: 0,
    flags: {
        api_rate_limit_size: 'm',
        environments_max: 2,
        has_otel: false,
        has_sync_variants: false,
        connections_max: 10,
        records_max: 100_000,
        proxy_max: 100_000,
        function_executions_max: 100_000,
        function_compute_gbms_max: 50_000_000,
        webhook_forwards_max: 100_000,
        function_logs_max: 100_000,
        name: 'free-v2',
        sync_frequency_secs_min: 3600,
        auto_idle: true,
        monthly_actions_max: 1000,
        monthly_active_records_max: 5000,
        has_webhooks_script: false,
        has_webhooks_forward: false,
        can_override_docs_connect_url: false,
        can_customize_connect_ui_theme: false,
        can_disable_connect_ui_watermark: false
    }
};

export const starterV2Plan: PlanDefinition = {
    code: 'starter-v2',
    orbId: 'starter',
    orbVersion: 6,
    isPaid: true,
    title: 'Starter',
    description: 'For small teams.',
    prevPlan: ['free-v2'],
    nextPlan: ['growth-v2'],
    canChange: true,
    basePrice: 50,
    flags: {
        api_rate_limit_size: 'l',
        environments_max: 3,
        has_otel: false,
        has_sync_variants: false,
        name: 'starter-v2',
        sync_frequency_secs_min: 3600,
        connections_max: null,
        records_max: null,
        proxy_max: null,
        function_executions_max: null,
        function_compute_gbms_max: null,
        webhook_forwards_max: null,
        function_logs_max: null,
        auto_idle: false,
        monthly_actions_max: null,
        monthly_active_records_max: null,
        trial_start_at: null,
        trial_end_at: null,
        trial_end_notified_at: null,
        trial_extension_count: 0,
        trial_expired: null,
        has_webhooks_script: false,
        has_webhooks_forward: false,
        can_override_docs_connect_url: false,
        can_customize_connect_ui_theme: false,
        can_disable_connect_ui_watermark: false
    }
};

export const growthV2Plan: PlanDefinition = {
    code: 'growth-v2',
    orbId: 'growth',
    orbVersion: 4,
    isPaid: true,
    title: 'Growth',
    description: 'For growing teams.',
    prevPlan: ['free-v2', 'starter-v2'],
    nextPlan: null,
    canChange: true,
    basePrice: 500,
    flags: {
        api_rate_limit_size: 'l',
        environments_max: 10,
        has_otel: true,
        has_sync_variants: true,
        name: 'growth-v2',
        sync_frequency_secs_min: 30,
        auto_idle: false,
        connections_max: null,
        records_max: null,
        proxy_max: null,
        function_executions_max: null,
        function_compute_gbms_max: null,
        webhook_forwards_max: null,
        function_logs_max: null,
        monthly_actions_max: null,
        monthly_active_records_max: null,
        trial_start_at: null,
        trial_end_at: null,
        trial_end_notified_at: null,
        trial_extension_count: 0,
        trial_expired: null,
        has_webhooks_script: true,
        has_webhooks_forward: true,
        can_override_docs_connect_url: false,
        can_customize_connect_ui_theme: true,
        can_disable_connect_ui_watermark: true
    }
};

/**
 * Enterprise plan - Custom needs
 */

export const enterprisePlan: PlanDefinition = {
    code: 'enterprise',
    title: 'Enterprise',
    description: 'For custom needs.',
    isPaid: true,
    prevPlan: null,
    nextPlan: null,
    canChange: false,
    cta: 'Contact Us',
    orbId: 'enterprise',
    flags: {
        api_rate_limit_size: '2xl',
        environments_max: 10,
        has_otel: true,
        has_sync_variants: true,
        name: 'enterprise',
        sync_frequency_secs_min: 30,
        connections_max: null,
        records_max: null,
        proxy_max: null,
        function_executions_max: null,
        function_compute_gbms_max: null,
        webhook_forwards_max: null,
        function_logs_max: null,
        auto_idle: false,
        monthly_actions_max: null,
        monthly_active_records_max: null,
        trial_start_at: null,
        trial_end_at: null,
        trial_end_notified_at: null,
        trial_extension_count: 0,
        trial_expired: null,
        has_webhooks_script: true,
        has_webhooks_forward: true,
        can_override_docs_connect_url: false,
        can_customize_connect_ui_theme: true,
        can_disable_connect_ui_watermark: true
    }
};

/**
 * Legacy Orb plans
 */

export const freeV1Plan: PlanDefinition = {
    code: 'free-v1',
    orbId: 'free',
    orbVersion: 1,
    title: 'Free (Legacy)',
    description: 'For hobby and testing.',
    isPaid: false,
    prevPlan: null,
    nextPlan: null,
    hidden: true,
    canChange: false,
    basePrice: 0,
    flags: {
        api_rate_limit_size: 'm',
        environments_max: 2,
        has_otel: false,
        has_sync_variants: false,
        connections_max: 10,
        records_max: 100_000,
        proxy_max: 100_000,
        function_executions_max: 100_000,
        function_compute_gbms_max: 50_000_000,
        webhook_forwards_max: 100_000,
        function_logs_max: 100_000,
        name: 'free-v1',
        sync_frequency_secs_min: 3600,
        auto_idle: true,
        monthly_actions_max: 1000,
        monthly_active_records_max: 5000,
        has_webhooks_script: false,
        has_webhooks_forward: false,
        can_override_docs_connect_url: false,
        can_customize_connect_ui_theme: false,
        can_disable_connect_ui_watermark: false
    }
};

export const starterV1Plan: PlanDefinition = {
    code: 'starter-v1',
    orbId: 'starter',
    orbVersion: [1, 2, 3, 4, 5],
    title: 'Starter (Legacy)',
    description: 'For small teams.',
    isPaid: true,
    prevPlan: ['free-v2'],
    nextPlan: null,
    canChange: false,
    hidden: true,
    basePrice: 50,
    flags: {
        api_rate_limit_size: 'l',
        environments_max: 3,
        has_otel: false,
        has_sync_variants: false,
        name: 'starter-v1',
        sync_frequency_secs_min: 3600,
        connections_max: null,
        records_max: null,
        proxy_max: null,
        function_executions_max: null,
        function_compute_gbms_max: null,
        webhook_forwards_max: null,
        function_logs_max: null,
        auto_idle: false,
        monthly_actions_max: null,
        monthly_active_records_max: null,
        trial_start_at: null,
        trial_end_at: null,
        trial_end_notified_at: null,
        trial_extension_count: 0,
        trial_expired: null,
        has_webhooks_script: false,
        has_webhooks_forward: false,
        can_override_docs_connect_url: false,
        can_customize_connect_ui_theme: false,
        can_disable_connect_ui_watermark: false
    }
};

export const growthV1Plan: PlanDefinition = {
    code: 'growth-v1',
    orbId: 'growth',
    orbVersion: [1, 2, 3],
    title: 'Growth (Legacy)',
    description: 'For growing teams.',
    isPaid: true,
    prevPlan: ['free-v2'],
    nextPlan: null,
    canChange: false,
    hidden: true,
    basePrice: 500,
    flags: {
        api_rate_limit_size: 'l',
        environments_max: 10,
        has_otel: true,
        has_sync_variants: true,
        name: 'growth-v1',
        sync_frequency_secs_min: 30,
        auto_idle: false,
        connections_max: null,
        records_max: null,
        proxy_max: null,
        function_executions_max: null,
        function_compute_gbms_max: null,
        webhook_forwards_max: null,
        function_logs_max: null,
        monthly_actions_max: null,
        monthly_active_records_max: null,
        trial_start_at: null,
        trial_end_at: null,
        trial_end_notified_at: null,
        trial_extension_count: 0,
        trial_expired: null,
        has_webhooks_script: true,
        has_webhooks_forward: true,
        can_override_docs_connect_url: false,
        can_customize_connect_ui_theme: true,
        can_disable_connect_ui_watermark: true
    }
};

/**
 * Legacy non-Orb plans
 */
export const starterLegacyPlan: PlanDefinition = {
    code: 'starter-legacy',
    title: 'Starter (legacy)',
    description: 'Tailored to your scale.',
    isPaid: true,
    prevPlan: [],
    nextPlan: [],
    canChange: false,
    hidden: true,
    flags: {
        api_rate_limit_size: 'l',
        environments_max: 3,
        has_otel: false,
        has_sync_variants: true,
        name: 'starter-legacy',
        sync_frequency_secs_min: 30,
        connections_max: null,
        records_max: null,
        proxy_max: null,
        function_executions_max: null,
        function_compute_gbms_max: null,
        webhook_forwards_max: null,
        function_logs_max: null,
        auto_idle: false,
        monthly_actions_max: null,
        monthly_active_records_max: null,
        trial_start_at: null,
        trial_end_at: null,
        trial_end_notified_at: null,
        trial_extension_count: 0,
        trial_expired: null,
        has_webhooks_script: true,
        has_webhooks_forward: true,
        can_override_docs_connect_url: false,
        can_customize_connect_ui_theme: false,
        can_disable_connect_ui_watermark: false
    }
};
export const scaleLegacyPlan: PlanDefinition = {
    code: 'scale-legacy',
    title: 'Scale (legacy)',
    description: 'Tailored to your scale.',
    isPaid: true,
    prevPlan: [],
    nextPlan: [],
    canChange: false,
    hidden: true,
    flags: {
        api_rate_limit_size: 'l',
        environments_max: 3,
        has_otel: false,
        has_sync_variants: true,
        name: 'scale-legacy',
        sync_frequency_secs_min: 30,
        connections_max: null,
        records_max: null,
        proxy_max: null,
        function_executions_max: null,
        function_compute_gbms_max: null,
        webhook_forwards_max: null,
        function_logs_max: null,
        auto_idle: false,
        monthly_actions_max: null,
        monthly_active_records_max: null,
        trial_start_at: null,
        trial_end_at: null,
        trial_end_notified_at: null,
        trial_extension_count: 0,
        trial_expired: null,
        has_webhooks_script: true,
        has_webhooks_forward: true,
        can_override_docs_connect_url: false,
        can_customize_connect_ui_theme: false,
        can_disable_connect_ui_watermark: false
    }
};
export const growthLegacyPlan: PlanDefinition = {
    code: 'growth-legacy',
    title: 'Growth (legacy)',
    description: 'Tailored to your scale.',
    isPaid: true,
    prevPlan: [],
    nextPlan: [],
    canChange: false,
    hidden: true,
    flags: {
        api_rate_limit_size: 'l',
        environments_max: 3,
        has_otel: false,
        has_sync_variants: true,
        name: 'growth-legacy',
        sync_frequency_secs_min: 30,
        connections_max: null,
        records_max: null,
        proxy_max: null,
        function_executions_max: null,
        function_compute_gbms_max: null,
        webhook_forwards_max: null,
        function_logs_max: null,
        auto_idle: false,
        monthly_actions_max: null,
        monthly_active_records_max: null,
        trial_start_at: null,
        trial_end_at: null,
        trial_end_notified_at: null,
        trial_extension_count: 0,
        trial_expired: null,
        has_webhooks_script: true,
        has_webhooks_forward: true,
        can_override_docs_connect_url: false,
        can_customize_connect_ui_theme: true,
        can_disable_connect_ui_watermark: true
    }
};

export const plansList: PlanDefinition[] = [
    // Latest plans
    freeV2Plan,
    starterV2Plan,
    growthV2Plan,

    // Enterprise plan - Custom needs
    enterprisePlan,

    // Legacy Orb plans
    freeV1Plan,
    starterV1Plan,
    growthV1Plan,

    // Legacy non-Orb plans
    starterLegacyPlan,
    scaleLegacyPlan,
    growthLegacyPlan
];
