// ---------------------------
// This file was generated by Nango (v0.59.7)
// You can version this file
// ---------------------------

export interface GithubIssue {
  id: string;
  owner: string;
  repo: string;
  issue_number: number;
  title: string;
  state: string;
  author: string;
  author_id: number;
  body: string;
  date_created: string;
  date_last_modified: string;
};

export interface ActionInput_github_demo_createIssue {
  id: string;
  owner: string;
  repo: string;
  issue_number: number;
  title: string;
  state: string;
  author: string;
  author_id: number;
  body: string;
  date_created: string;
  date_last_modified: string;
};

export interface ActionOutput_github_demo_createIssue {
  id: string;
  owner: string;
  repo: string;
  issue_number: number;
  title: string;
  state: string;
  author: string;
  author_id: number;
  body: string;
  date_created: string;
  date_last_modified: string;
};
