export enum LogActionEnum {
    ACCOUNT = 'account',
    ACTION = 'action',
    ANALYTICS = 'analytics',
    AUTH = 'auth',
    DATABASE = 'database',
    FILE = 'file',
    FULL_SYNC = 'full sync',
    INFRASTRUCTURE = 'infrastructure',
    INTERNAL_AUTHORIZATION = 'internal authorization',
    PAUSE_SYNC = 'pause sync',
    PROXY = 'proxy',
    RESTART_SYNC = 'restart sync',
    CANCEL_SYNC = 'cancel sync',
    SYNC = 'sync',
    SYNC_INIT = 'sync init',
    SYNC_CLIENT = 'sync client',
    SYNC_DEPLOY = 'sync deploy',
    ON_EVENT_SCRIPT = 'on event script',
    TOKEN = 'token',
    TRIGGER_SYNC = 'trigger sync',
    TRIGGER_FULL_SYNC = 'trigger full sync',
    WEBHOOK = 'webhook'
}
