export const countryCodes: { value: string; label: string }[] = [
    { value: 'AD', label: 'Andorra' },
    { value: 'AE', label: 'United Arab Emirates' },
    { value: 'AL', label: 'Albania' },
    { value: 'AM', label: 'Armenia' },
    { value: 'AO', label: 'Angola' },
    { value: 'AR', label: 'Argentina' },
    { value: 'AT', label: 'Austria' },
    { value: 'AU', label: 'Australia' },
    { value: 'AW', label: 'Aruba' },
    { value: 'AZ', label: 'Azerbaijan' },
    { value: 'BA', label: 'Bosnia and Herzegovina' },
    { value: 'BB', label: 'Barbados' },
    { value: 'BD', label: 'Bangladesh' },
    { value: 'BE', label: 'Belgium' },
    { value: 'BF', label: 'Burkina Faso' },
    { value: 'BG', label: 'Bulgaria' },
    { value: 'BH', label: 'Bahrain' },
    { value: 'BJ', label: 'Benin' },
    { value: 'BO', label: 'Bolivia' },
    { value: 'BR', label: 'Brazil' },
    { value: 'BS', label: 'Bahamas' },
    { value: 'BY', label: 'Belarus' },
    { value: 'CA', label: 'Canada' },
    { value: 'CD', label: 'DR Congo' },
    { value: 'CH', label: 'Switzerland' },
    { value: 'CL', label: 'Chile' },
    { value: 'CM', label: 'Cameroon' },
    { value: 'CN', label: 'China' },
    { value: 'CO', label: 'Colombia' },
    { value: 'CR', label: 'Costa Rica' },
    { value: 'CV', label: 'Cape Verde' },
    { value: 'CY', label: 'Cyprus' },
    { value: 'CZ', label: 'Czech Republic' },
    { value: 'DE', label: 'Germany' },
    { value: 'DK', label: 'Denmark' },
    { value: 'DO', label: 'Dominican Republic' },
    { value: 'EC', label: 'Ecuador' },
    { value: 'EE', label: 'Estonia' },
    { value: 'EG', label: 'Egypt' },
    { value: 'ES', label: 'Spain' },
    { value: 'ET', label: 'Ethiopia' },
    { value: 'EU', label: 'European Union' },
    { value: 'FI', label: 'Finland' },
    { value: 'FR', label: 'France' },
    { value: 'GB', label: 'United Kingdom' },
    { value: 'GE', label: 'Georgia' },
    { value: 'GN', label: 'Guinea' },
    { value: 'GR', label: 'Greece' },
    { value: 'HK', label: 'Hong Kong' },
    { value: 'HR', label: 'Croatia' },
    { value: 'HU', label: 'Hungary' },
    { value: 'ID', label: 'Indonesia' },
    { value: 'IE', label: 'Ireland' },
    { value: 'IL', label: 'Israel' },
    { value: 'IN', label: 'India' },
    { value: 'IS', label: 'Iceland' },
    { value: 'IT', label: 'Italy' },
    { value: 'JP', label: 'Japan' },
    { value: 'KE', label: 'Kenya' },
    { value: 'KG', label: 'Kyrgyzstan' },
    { value: 'KH', label: 'Cambodia' },
    { value: 'KR', label: 'South Korea' },
    { value: 'KZ', label: 'Kazakhstan' },
    { value: 'LA', label: 'Laos' },
    { value: 'LI', label: 'Liechtenstein' },
    { value: 'LT', label: 'Lithuania' },
    { value: 'LU', label: 'Luxembourg' },
    { value: 'LV', label: 'Latvia' },
    { value: 'MA', label: 'Morocco' },
    { value: 'MD', label: 'Moldova' },
    { value: 'ME', label: 'Montenegro' },
    { value: 'MK', label: 'North Macedonia' },
    { value: 'MR', label: 'Mauritania' },
    { value: 'MT', label: 'Malta' },
    { value: 'MX', label: 'Mexico' },
    { value: 'MY', label: 'Malaysia' },
    { value: 'NG', label: 'Nigeria' },
    { value: 'NL', label: 'Netherlands' },
    { value: 'NO', label: 'Norway' },
    { value: 'NP', label: 'Nepal' },
    { value: 'NZ', label: 'New Zealand' },
    { value: 'OM', label: 'Oman' },
    { value: 'PE', label: 'Peru' },
    { value: 'PH', label: 'Philippines' },
    { value: 'PL', label: 'Poland' },
    { value: 'PT', label: 'Portugal' },
    { value: 'RO', label: 'Romania' },
    { value: 'RS', label: 'Serbia' },
    { value: 'RU', label: 'Russia' },
    { value: 'SA', label: 'Saudi Arabia' },
    { value: 'SE', label: 'Sweden' },
    { value: 'SG', label: 'Singapore' },
    { value: 'SI', label: 'Slovenia' },
    { value: 'SK', label: 'Slovakia' },
    { value: 'SN', label: 'Senegal' },
    { value: 'SR', label: 'Suriname' },
    { value: 'SV', label: 'El Salvador' },
    { value: 'TH', label: 'Thailand' },
    { value: 'TJ', label: 'Tajikistan' },
    { value: 'TR', label: 'Turkey' },
    { value: 'TW', label: 'Taiwan' },
    { value: 'TZ', label: 'Tanzania' },
    { value: 'UA', label: 'Ukraine' },
    { value: 'UG', label: 'Uganda' },
    { value: 'US', label: 'United States' },
    { value: 'UY', label: 'Uruguay' },
    { value: 'UZ', label: 'Uzbekistan' },
    { value: 'VE', label: 'Venezuela' },
    { value: 'VN', label: 'Vietnam' },
    { value: 'ZA', label: 'South Africa' },
    { value: 'ZM', label: 'Zambia' },
    { value: 'ZW', label: 'Zimbabwe' }
];

export const taxIdTypes: { value: string; label: string; placeholder: string }[] = [
    { value: 'ad_nrt', label: 'Andorra NRT', placeholder: 'A-123456-Z' },
    { value: 'ae_trn', label: 'UAE TRN', placeholder: '123456789012345' },
    { value: 'al_tin', label: 'Albania TIN', placeholder: 'J12345678N' },
    { value: 'am_tin', label: 'Armenia TIN', placeholder: '12345678' },
    { value: 'ao_tin', label: 'Angola TIN', placeholder: '123456789' },
    { value: 'ar_cuit', label: 'Argentina CUIT', placeholder: '12-34567890-1' },
    { value: 'au_abn', label: 'Australia ABN', placeholder: '12 345 678 901' },
    { value: 'au_arn', label: 'Australia ARN', placeholder: '123456789012' },
    { value: 'aw_tin', label: 'Aruba TIN', placeholder: '123456789' },
    { value: 'az_tin', label: 'Azerbaijan TIN', placeholder: '1234567890' },
    { value: 'ba_tin', label: 'Bosnia TIN', placeholder: '123456789' },
    { value: 'bb_tin', label: 'Barbados TIN', placeholder: '123456789' },
    { value: 'bd_bin', label: 'Bangladesh BIN', placeholder: '123456789-0123' },
    { value: 'bf_ifu', label: 'Burkina Faso IFU', placeholder: '12345678901' },
    { value: 'bg_uic', label: 'Bulgaria UIC', placeholder: '123456789' },
    { value: 'bh_vat', label: 'Bahrain VAT', placeholder: '123456789012345' },
    { value: 'bj_ifu', label: 'Benin IFU', placeholder: '12345678901' },
    { value: 'bo_tin', label: 'Bolivia TIN', placeholder: '1234567' },
    { value: 'br_cnpj', label: 'Brazil CNPJ', placeholder: '01.234.567/8901-23' },
    { value: 'br_cpf', label: 'Brazil CPF', placeholder: '123.456.789-09' },
    { value: 'bs_tin', label: 'Bahamas TIN', placeholder: '123456789' },
    { value: 'by_tin', label: 'Belarus TIN', placeholder: '123456789' },
    { value: 'ca_bn', label: 'Canada BN', placeholder: '123456789' },
    { value: 'ca_gst_hst', label: 'Canada GST/HST', placeholder: '123456789RT0001' },
    { value: 'ca_pst_bc', label: 'Canada PST (BC)', placeholder: 'PST-1234-5678' },
    { value: 'ca_pst_mb', label: 'Canada PST (MB)', placeholder: '123456-1' },
    { value: 'ca_pst_sk', label: 'Canada PST (SK)', placeholder: '1234567' },
    { value: 'ca_qst', label: 'Canada QST', placeholder: '1234567890TQ0001' },
    { value: 'cd_nif', label: 'DR Congo NIF', placeholder: 'A1234567B' },
    { value: 'ch_uid', label: 'Switzerland UID', placeholder: 'CHE-123.456.789' },
    { value: 'ch_vat', label: 'Switzerland VAT', placeholder: 'CHE-123.456.789 MWST' },
    { value: 'cl_tin', label: 'Chile TIN', placeholder: '12.345.678-K' },
    { value: 'cm_niu', label: 'Cameroon NIU', placeholder: 'M123456789' },
    { value: 'cn_tin', label: 'China TIN', placeholder: '123456789012345678' },
    { value: 'co_nit', label: 'Colombia NIT', placeholder: '123.456.789-0' },
    { value: 'cr_tin', label: 'Costa Rica TIN', placeholder: '1-234-567890' },
    { value: 'cv_nif', label: 'Cape Verde NIF', placeholder: 'A123456789' },
    { value: 'de_stn', label: 'Germany STN', placeholder: '1234567890' },
    { value: 'do_rcn', label: 'Dominican Republic RCN', placeholder: '1-23-45678-9' },
    { value: 'ec_ruc', label: 'Ecuador RUC', placeholder: '1234567890001' },
    { value: 'eg_tin', label: 'Egypt TIN', placeholder: '123456789' },
    { value: 'es_cif', label: 'Spain CIF', placeholder: 'A12345678' },
    { value: 'et_tin', label: 'Ethiopia TIN', placeholder: '1234567890' },
    { value: 'eu_oss_vat', label: 'EU OSS VAT', placeholder: 'EU123456789' },
    { value: 'eu_vat', label: 'European VAT', placeholder: 'EU123456789' },
    { value: 'gb_vat', label: 'UK VAT', placeholder: 'GB123456789' },
    { value: 'ge_vat', label: 'Georgia VAT', placeholder: '123456789' },
    { value: 'gn_nif', label: 'Guinea NIF', placeholder: '123456789' },
    { value: 'hk_br', label: 'Hong Kong BR', placeholder: '12345678' },
    { value: 'hr_oib', label: 'Croatia OIB', placeholder: '12345678901' },
    { value: 'hu_tin', label: 'Hungary TIN', placeholder: '12345678-1-23' },
    { value: 'id_npwp', label: 'Indonesia NPWP', placeholder: '12.345.678.9-012.345' },
    { value: 'il_vat', label: 'Israel VAT', placeholder: '123456789' },
    { value: 'in_gst', label: 'India GST', placeholder: '12ABCDE1234F1Z5' },
    { value: 'is_vat', label: 'Iceland VAT', placeholder: '123456' },
    { value: 'jp_cn', label: 'Japan CN', placeholder: '1234567890123' },
    { value: 'jp_rn', label: 'Japan RN', placeholder: '12345' },
    { value: 'jp_trn', label: 'Japan TRN', placeholder: 'T1234567890123' },
    { value: 'ke_pin', label: 'Kenya PIN', placeholder: 'P123456789A' },
    { value: 'kg_tin', label: 'Kyrgyzstan TIN', placeholder: '12345678901234' },
    { value: 'kh_tin', label: 'Cambodia TIN', placeholder: 'L001-123456789' },
    { value: 'kr_brn', label: 'South Korea BRN', placeholder: '123-45-67890' },
    { value: 'kz_bin', label: 'Kazakhstan BIN', placeholder: '123456789012' },
    { value: 'la_tin', label: 'Laos TIN', placeholder: '1234567890' },
    { value: 'li_uid', label: 'Liechtenstein UID', placeholder: 'CHE-123.456.789' },
    { value: 'li_vat', label: 'Liechtenstein VAT', placeholder: '12345' },
    { value: 'ma_vat', label: 'Morocco VAT', placeholder: '12345678' },
    { value: 'md_vat', label: 'Moldova VAT', placeholder: '1234567' },
    { value: 'me_pib', label: 'Montenegro PIB', placeholder: '12345678' },
    { value: 'mk_vat', label: 'North Macedonia VAT', placeholder: 'MK1234567890' },
    { value: 'mr_nif', label: 'Mauritania NIF', placeholder: '12345678901' },
    { value: 'mx_rfc', label: 'Mexico RFC', placeholder: 'ABCD123456EFG' },
    { value: 'my_frp', label: 'Malaysia FRP', placeholder: '12345678' },
    { value: 'my_itn', label: 'Malaysia ITN', placeholder: 'C 1234567890' },
    { value: 'my_sst', label: 'Malaysia SST', placeholder: 'A12-3456-78901234' },
    { value: 'ng_tin', label: 'Nigeria TIN', placeholder: '12345678-0001' },
    { value: 'no_vat', label: 'Norway VAT', placeholder: '123456789MVA' },
    { value: 'no_voec', label: 'Norway VOEC', placeholder: '1234567' },
    { value: 'np_pan', label: 'Nepal PAN', placeholder: '123456789' },
    { value: 'nz_gst', label: 'New Zealand GST', placeholder: '123456789' },
    { value: 'om_vat', label: 'Oman VAT', placeholder: 'OM1234567890' },
    { value: 'pe_ruc', label: 'Peru RUC', placeholder: '12345678901' },
    { value: 'ph_tin', label: 'Philippines TIN', placeholder: '123-456-789-000' },
    { value: 'pl_nip', label: 'Poland NIP', placeholder: '1234567890' },
    { value: 'ro_tin', label: 'Romania TIN', placeholder: '1234567890' },
    { value: 'rs_pib', label: 'Serbia PIB', placeholder: '123456789' },
    { value: 'ru_inn', label: 'Russia INN', placeholder: '1234567890' },
    { value: 'ru_kpp', label: 'Russia KPP', placeholder: '123456789' },
    { value: 'sa_vat', label: 'Saudi Arabia VAT', placeholder: '123456789012345' },
    { value: 'sg_gst', label: 'Singapore GST', placeholder: 'M12345678X' },
    { value: 'sg_uen', label: 'Singapore UEN', placeholder: '123456789A' },
    { value: 'si_tin', label: 'Slovenia TIN', placeholder: '12345678' },
    { value: 'sn_ninea', label: 'Senegal NINEA', placeholder: '1234567890123' },
    { value: 'sr_fin', label: 'Suriname FIN', placeholder: '123456789' },
    { value: 'sv_nit', label: 'El Salvador NIT', placeholder: '1234-567890-123-4' },
    { value: 'th_vat', label: 'Thailand VAT', placeholder: '1234567890123' },
    { value: 'tj_tin', label: 'Tajikistan TIN', placeholder: '123456789' },
    { value: 'tr_tin', label: 'Turkey TIN', placeholder: '1234567890' },
    { value: 'tw_vat', label: 'Taiwan VAT', placeholder: '12345678' },
    { value: 'tz_vat', label: 'Tanzania VAT', placeholder: '12-345678-A' },
    { value: 'ua_vat', label: 'Ukraine VAT', placeholder: '123456789' },
    { value: 'ug_tin', label: 'Uganda TIN', placeholder: '1234567890A' },
    { value: 'us_ein', label: 'United States EIN', placeholder: '12-3456789' },
    { value: 'uy_ruc', label: 'Uruguay RUC', placeholder: '123456789012' },
    { value: 'uz_tin', label: 'Uzbekistan TIN', placeholder: '123456789' },
    { value: 'uz_vat', label: 'Uzbekistan VAT', placeholder: '123456789' },
    { value: 've_rif', label: 'Venezuela RIF', placeholder: 'J-12345678-9' },
    { value: 'vn_tin', label: 'Vietnam TIN', placeholder: '1234567890' },
    { value: 'za_vat', label: 'South Africa VAT', placeholder: '4123456789' },
    { value: 'zm_tin', label: 'Zambia TIN', placeholder: '1234567890' },
    { value: 'zw_tin', label: 'Zimbabwe TIN', placeholder: '1234567890' }
];
