export const countryCodes: { value: string; label: string }[] = [
    { value: 'AD', label: 'Andorra' },
    { value: 'AE', label: 'United Arab Emirates' },
    { value: 'AL', label: 'Albania' },
    { value: 'AM', label: 'Armenia' },
    { value: 'AO', label: 'Angola' },
    { value: 'AR', label: 'Argentina' },
    { value: 'AT', label: 'Austria' },
    { value: 'AU', label: 'Australia' },
    { value: 'AW', label: 'Aruba' },
    { value: 'AZ', label: 'Azerbaijan' },
    { value: 'BA', label: 'Bosnia and Herzegovina' },
    { value: 'BB', label: 'Barbados' },
    { value: 'BD', label: 'Bangladesh' },
    { value: 'BE', label: 'Belgium' },
    { value: 'BF', label: 'Burkina Faso' },
    { value: 'BG', label: 'Bulgaria' },
    { value: 'BH', label: 'Bahrain' },
    { value: 'BJ', label: 'Benin' },
    { value: 'BO', label: 'Bolivia' },
    { value: 'BR', label: 'Brazil' },
    { value: 'BS', label: 'Bahamas' },
    { value: 'BY', label: 'Belarus' },
    { value: 'CA', label: 'Canada' },
    { value: 'CD', label: 'DR Congo' },
    { value: 'CH', label: 'Switzerland' },
    { value: 'CL', label: 'Chile' },
    { value: 'CM', label: 'Cameroon' },
    { value: 'CN', label: 'China' },
    { value: 'CO', label: 'Colombia' },
    { value: 'CR', label: 'Costa Rica' },
    { value: 'CV', label: 'Cape Verde' },
    { value: 'CY', label: 'Cyprus' },
    { value: 'CZ', label: 'Czech Republic' },
    { value: 'DE', label: 'Germany' },
    { value: 'DK', label: 'Denmark' },
    { value: 'DO', label: 'Dominican Republic' },
    { value: 'EC', label: 'Ecuador' },
    { value: 'EE', label: 'Estonia' },
    { value: 'EG', label: 'Egypt' },
    { value: 'ES', label: 'Spain' },
    { value: 'ET', label: 'Ethiopia' },
    { value: 'EU', label: 'European Union' },
    { value: 'FI', label: 'Finland' },
    { value: 'FR', label: 'France' },
    { value: 'GB', label: 'United Kingdom' },
    { value: 'GE', label: 'Georgia' },
    { value: 'GN', label: 'Guinea' },
    { value: 'GR', label: 'Greece' },
    { value: 'HK', label: 'Hong Kong' },
    { value: 'HR', label: 'Croatia' },
    { value: 'HU', label: 'Hungary' },
    { value: 'ID', label: 'Indonesia' },
    { value: 'IE', label: 'Ireland' },
    { value: 'IL', label: 'Israel' },
    { value: 'IN', label: 'India' },
    { value: 'IS', label: 'Iceland' },
    { value: 'IT', label: 'Italy' },
    { value: 'JP', label: 'Japan' },
    { value: 'KE', label: 'Kenya' },
    { value: 'KG', label: 'Kyrgyzstan' },
    { value: 'KH', label: 'Cambodia' },
    { value: 'KR', label: 'South Korea' },
    { value: 'KZ', label: 'Kazakhstan' },
    { value: 'LA', label: 'Laos' },
    { value: 'LI', label: 'Liechtenstein' },
    { value: 'LT', label: 'Lithuania' },
    { value: 'LU', label: 'Luxembourg' },
    { value: 'LV', label: 'Latvia' },
    { value: 'MA', label: 'Morocco' },
    { value: 'MD', label: 'Moldova' },
    { value: 'ME', label: 'Montenegro' },
    { value: 'MK', label: 'North Macedonia' },
    { value: 'MR', label: 'Mauritania' },
    { value: 'MT', label: 'Malta' },
    { value: 'MX', label: 'Mexico' },
    { value: 'MY', label: 'Malaysia' },
    { value: 'NG', label: 'Nigeria' },
    { value: 'NL', label: 'Netherlands' },
    { value: 'NO', label: 'Norway' },
    { value: 'NP', label: 'Nepal' },
    { value: 'NZ', label: 'New Zealand' },
    { value: 'OM', label: 'Oman' },
    { value: 'PE', label: 'Peru' },
    { value: 'PH', label: 'Philippines' },
    { value: 'PL', label: 'Poland' },
    { value: 'PT', label: 'Portugal' },
    { value: 'RO', label: 'Romania' },
    { value: 'RS', label: 'Serbia' },
    { value: 'RU', label: 'Russia' },
    { value: 'SA', label: 'Saudi Arabia' },
    { value: 'SE', label: 'Sweden' },
    { value: 'SG', label: 'Singapore' },
    { value: 'SI', label: 'Slovenia' },
    { value: 'SK', label: 'Slovakia' },
    { value: 'SN', label: 'Senegal' },
    { value: 'SR', label: 'Suriname' },
    { value: 'SV', label: 'El Salvador' },
    { value: 'TH', label: 'Thailand' },
    { value: 'TJ', label: 'Tajikistan' },
    { value: 'TR', label: 'Turkey' },
    { value: 'TW', label: 'Taiwan' },
    { value: 'TZ', label: 'Tanzania' },
    { value: 'UA', label: 'Ukraine' },
    { value: 'UG', label: 'Uganda' },
    { value: 'US', label: 'United States' },
    { value: 'UY', label: 'Uruguay' },
    { value: 'UZ', label: 'Uzbekistan' },
    { value: 'VE', label: 'Venezuela' },
    { value: 'VN', label: 'Vietnam' },
    { value: 'ZA', label: 'South Africa' },
    { value: 'ZM', label: 'Zambia' },
    { value: 'ZW', label: 'Zimbabwe' }
];

export const taxIdTypes: { value: string; label: string }[] = [
    { value: 'ad_nrt', label: 'Andorra NRT' },
    { value: 'ae_trn', label: 'UAE TRN' },
    { value: 'al_tin', label: 'Albania TIN' },
    { value: 'am_tin', label: 'Armenia TIN' },
    { value: 'ao_tin', label: 'Angola TIN' },
    { value: 'ar_cuit', label: 'Argentina CUIT' },
    { value: 'au_abn', label: 'Australia ABN' },
    { value: 'au_arn', label: 'Australia ARN' },
    { value: 'aw_tin', label: 'Aruba TIN' },
    { value: 'az_tin', label: 'Azerbaijan TIN' },
    { value: 'ba_tin', label: 'Bosnia TIN' },
    { value: 'bb_tin', label: 'Barbados TIN' },
    { value: 'bd_bin', label: 'Bangladesh BIN' },
    { value: 'bf_ifu', label: 'Burkina Faso IFU' },
    { value: 'bg_uic', label: 'Bulgaria UIC' },
    { value: 'bh_vat', label: 'Bahrain VAT' },
    { value: 'bj_ifu', label: 'Benin IFU' },
    { value: 'bo_tin', label: 'Bolivia TIN' },
    { value: 'br_cnpj', label: 'Brazil CNPJ' },
    { value: 'br_cpf', label: 'Brazil CPF' },
    { value: 'bs_tin', label: 'Bahamas TIN' },
    { value: 'by_tin', label: 'Belarus TIN' },
    { value: 'ca_bn', label: 'Canada BN' },
    { value: 'ca_gst_hst', label: 'Canada GST/HST' },
    { value: 'ca_pst_bc', label: 'Canada PST (BC)' },
    { value: 'ca_pst_mb', label: 'Canada PST (MB)' },
    { value: 'ca_pst_sk', label: 'Canada PST (SK)' },
    { value: 'ca_qst', label: 'Canada QST' },
    { value: 'cd_nif', label: 'DR Congo NIF' },
    { value: 'ch_uid', label: 'Switzerland UID' },
    { value: 'ch_vat', label: 'Switzerland VAT' },
    { value: 'cl_tin', label: 'Chile TIN' },
    { value: 'cm_niu', label: 'Cameroon NIU' },
    { value: 'cn_tin', label: 'China TIN' },
    { value: 'co_nit', label: 'Colombia NIT' },
    { value: 'cr_tin', label: 'Costa Rica TIN' },
    { value: 'cv_nif', label: 'Cape Verde NIF' },
    { value: 'de_stn', label: 'Germany STN' },
    { value: 'do_rcn', label: 'Dominican Republic RCN' },
    { value: 'ec_ruc', label: 'Ecuador RUC' },
    { value: 'eg_tin', label: 'Egypt TIN' },
    { value: 'es_cif', label: 'Spain CIF' },
    { value: 'et_tin', label: 'Ethiopia TIN' },
    { value: 'eu_oss_vat', label: 'EU OSS VAT' },
    { value: 'eu_vat', label: 'European VAT' },
    { value: 'gb_vat', label: 'UK VAT' },
    { value: 'ge_vat', label: 'Georgia VAT' },
    { value: 'gn_nif', label: 'Guinea NIF' },
    { value: 'hk_br', label: 'Hong Kong BR' },
    { value: 'hr_oib', label: 'Croatia OIB' },
    { value: 'hu_tin', label: 'Hungary TIN' },
    { value: 'id_npwp', label: 'Indonesia NPWP' },
    { value: 'il_vat', label: 'Israel VAT' },
    { value: 'in_gst', label: 'India GST' },
    { value: 'is_vat', label: 'Iceland VAT' },
    { value: 'jp_cn', label: 'Japan CN' },
    { value: 'jp_rn', label: 'Japan RN' },
    { value: 'jp_trn', label: 'Japan TRN' },
    { value: 'ke_pin', label: 'Kenya PIN' },
    { value: 'kg_tin', label: 'Kyrgyzstan TIN' },
    { value: 'kh_tin', label: 'Cambodia TIN' },
    { value: 'kr_brn', label: 'South Korea BRN' },
    { value: 'kz_bin', label: 'Kazakhstan BIN' },
    { value: 'la_tin', label: 'Laos TIN' },
    { value: 'li_uid', label: 'Liechtenstein UID' },
    { value: 'li_vat', label: 'Liechtenstein VAT' },
    { value: 'ma_vat', label: 'Morocco VAT' },
    { value: 'md_vat', label: 'Moldova VAT' },
    { value: 'me_pib', label: 'Montenegro PIB' },
    { value: 'mk_vat', label: 'North Macedonia VAT' },
    { value: 'mr_nif', label: 'Mauritania NIF' },
    { value: 'mx_rfc', label: 'Mexico RFC' },
    { value: 'my_frp', label: 'Malaysia FRP' },
    { value: 'my_itn', label: 'Malaysia ITN' },
    { value: 'my_sst', label: 'Malaysia SST' },
    { value: 'ng_tin', label: 'Nigeria TIN' },
    { value: 'no_vat', label: 'Norway VAT' },
    { value: 'no_voec', label: 'Norway VOEC' },
    { value: 'np_pan', label: 'Nepal PAN' },
    { value: 'nz_gst', label: 'New Zealand GST' },
    { value: 'om_vat', label: 'Oman VAT' },
    { value: 'pe_ruc', label: 'Peru RUC' },
    { value: 'ph_tin', label: 'Philippines TIN' },
    { value: 'pl_nip', label: 'Poland NIP' },
    { value: 'ro_tin', label: 'Romania TIN' },
    { value: 'rs_pib', label: 'Serbia PIB' },
    { value: 'ru_inn', label: 'Russia INN' },
    { value: 'ru_kpp', label: 'Russia KPP' },
    { value: 'sa_vat', label: 'Saudi Arabia VAT' },
    { value: 'sg_gst', label: 'Singapore GST' },
    { value: 'sg_uen', label: 'Singapore UEN' },
    { value: 'si_tin', label: 'Slovenia TIN' },
    { value: 'sn_ninea', label: 'Senegal NINEA' },
    { value: 'sr_fin', label: 'Suriname FIN' },
    { value: 'sv_nit', label: 'El Salvador NIT' },
    { value: 'th_vat', label: 'Thailand VAT' },
    { value: 'tj_tin', label: 'Tajikistan TIN' },
    { value: 'tr_tin', label: 'Turkey TIN' },
    { value: 'tw_vat', label: 'Taiwan VAT' },
    { value: 'tz_vat', label: 'Tanzania VAT' },
    { value: 'ua_vat', label: 'Ukraine VAT' },
    { value: 'ug_tin', label: 'Uganda TIN' },
    { value: 'us_ein', label: 'United States EIN' },
    { value: 'uy_ruc', label: 'Uruguay RUC' },
    { value: 'uz_tin', label: 'Uzbekistan TIN' },
    { value: 'uz_vat', label: 'Uzbekistan VAT' },
    { value: 've_rif', label: 'Venezuela RIF' },
    { value: 'vn_tin', label: 'Vietnam TIN' },
    { value: 'za_vat', label: 'South Africa VAT' },
    { value: 'zm_tin', label: 'Zambia TIN' },
    { value: 'zw_tin', label: 'Zimbabwe TIN' }
];
