import tokensJson from '../tokens.json';

import type { Meta, StoryObj } from '@storybook/react';

const meta: Meta = {
    title: 'Design System/Tokens/Typography',
    parameters: {
        layout: 'padded'
    }
};

export default meta;

// ─── Token derivation ────────────────────────────────────────────────────────

function capitalize(s: string): string {
    return s.charAt(0).toUpperCase() + s.slice(1);
}

interface TypeEntry {
    /** CSS class generated by the token pipeline, e.g. 'type-heading-lg' */
    className: string;
    /** Token path label, e.g. 'heading / lg' */
    name: string;
    /** Short usage hint — sourced from DESCRIPTIONS map, absent for unknown tokens */
    description?: string;
    /** True for mono tokens — renders a code sample instead of prose */
    mono?: boolean;
}

interface TypeSection {
    title: string;
    entries: TypeEntry[];
}

/**
 * Optional editorial descriptions keyed by class name.
 * New tokens without an entry here render without a description — they won't
 * cause drift or errors, they'll just show no hint text.
 */
const DESCRIPTIONS: Record<string, string> = {
    'type-heading-lg': 'page headings, hero titles',
    'type-heading-md': 'section headings',
    'type-heading-sm': 'sub-section headings',
    'type-text-regular-md': 'standard body text',
    'type-text-regular-sm': 'dense body / tables',
    'type-text-regular-xs': 'small body / captions',
    'type-text-medium-md': 'emphasized body text',
    'type-text-medium-sm': 'emphasized dense body',
    'type-text-medium-xs': 'emphasized small body',
    'type-label-lg': 'form labels, prominent chips',
    'type-label-md': 'badges, table headers',
    'type-label-sm': 'metadata, helper text',
    'type-label-xs': 'tag content, inline status',
    'type-label-xxs': 'finest micro labels — use sparingly',
    'type-code-regular-sm': 'inline code, IDs, slugs',
    'type-code-regular-xs': 'small inline code',
    'type-code-regular-xxs': 'finest mono',
    'type-code-medium-md': 'emphasized code',
    'type-code-medium-sm': 'emphasized inline code',
    'type-code-medium-xs': 'emphasized small inline code',
    'type-code-medium-xxs': 'emphasized finest mono'
};

function isMono(token: Record<string, unknown>): boolean {
    const value = token['$value'] as Record<string, string> | undefined;
    return value?.fontFamily?.toLowerCase().includes('mono') ?? false;
}

/**
 * Recursively collect TypeEntry items from a token group.
 * path accumulates the token path segments used to build the class name.
 */
function collectEntries(obj: Record<string, unknown>, path: string[]): TypeEntry[] {
    const entries: TypeEntry[] = [];
    for (const [key, value] of Object.entries(obj)) {
        if (key.startsWith('$')) continue;
        if (value && typeof value === 'object' && '$value' in value) {
            const className = 'type-' + [...path, key].join('-');
            entries.push({
                className,
                name: [...path, key].join(' / '),
                description: DESCRIPTIONS[className],
                mono: isMono(value as Record<string, unknown>)
            });
        } else if (value && typeof value === 'object') {
            entries.push(...collectEntries(value as Record<string, unknown>, [...path, key]));
        }
    }
    return entries;
}

/**
 * Build sections from the Typography token group in tokens.json.
 * Top-level groups with nested sub-groups (text, code) produce one section per sub-group.
 * Flat top-level groups (heading, label) produce a single section.
 */
function buildSections(typoGroup: Record<string, unknown>): TypeSection[] {
    const sections: TypeSection[] = [];
    for (const [key, value] of Object.entries(typoGroup)) {
        if (key.startsWith('$') || !value || typeof value !== 'object') continue;

        const children = Object.entries(value as Record<string, unknown>).filter(([k]) => !k.startsWith('$'));
        const hasSubGroups = children.some(([, v]) => v && typeof v === 'object' && !('$value' in v));

        if (hasSubGroups) {
            for (const [subKey, subValue] of children) {
                if (!subValue || typeof subValue !== 'object') continue;
                const entries = collectEntries(subValue as Record<string, unknown>, [key, subKey]);
                if (entries.length === 0) continue;
                const font = entries[0]?.mono ? 'Geist Mono' : 'Geist Sans';
                sections.push({ title: `${font} — ${capitalize(key)} · ${capitalize(subKey)}`, entries });
            }
        } else {
            const entries = collectEntries(value as Record<string, unknown>, [key]);
            if (entries.length === 0) continue;
            const font = entries[0]?.mono ? 'Geist Mono' : 'Geist Sans';
            sections.push({ title: `${font} — ${capitalize(key)}`, entries });
        }
    }
    return sections;
}

const typographyGroup = (tokensJson as Record<string, unknown>)['Typography'] as Record<string, unknown>;
const SECTIONS = buildSections(typographyGroup);

// ─── Components ─────────────────────────────────────────────────────────────

const SAMPLE_TEXT = 'The quick brown fox jumps over the lazy dog';
const SAMPLE_MONO = 'const api_key = "nango_live_abc123xyz";';

function TypeRow({ entry }: { entry: TypeEntry }) {
    return (
        <div className="grid grid-cols-[260px_1fr] gap-4 items-baseline py-3 border-b border-border-default">
            <div className="text-[11px] font-mono pt-0.5">
                <div className="font-medium text-text-secondary">{entry.name}</div>
                {entry.description && <div className="mt-1 font-normal text-text-muted">{entry.description}</div>}
            </div>
            <div className={`text-text-strong ${entry.className}`}>{entry.mono ? SAMPLE_MONO : SAMPLE_TEXT}</div>
        </div>
    );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
    return (
        <div className="mb-12">
            <h2 className="story-section-heading mb-3">{title}</h2>
            {children}
        </div>
    );
}

// ─── Stories ────────────────────────────────────────────────────────────────

type Story = StoryObj<typeof meta>;

export const TypeScale: Story = {
    name: 'Type Scale',
    render: () => (
        <div className="p-8">
            {SECTIONS.map((section) => (
                <Section key={section.title} title={section.title}>
                    {section.entries.map((e) => (
                        <TypeRow key={e.className} entry={e} />
                    ))}
                </Section>
            ))}
        </div>
    )
};

export const FontFamilies: Story = {
    name: 'Font Families',
    render: () => (
        <div className="max-w-[700px] p-8">
            <Section title="Geist Sans — UI text">
                <div className="text-[28px] font-sans text-text-strong leading-[1.5]">
                    ABCDEFGHIJKLMNOPQRSTUVWXYZ
                    <br />
                    abcdefghijklmnopqrstuvwxyz
                    <br />
                    0123456789 !@#$%^&amp;*()
                </div>
            </Section>
            <Section title="Geist Mono — Code, IDs, API keys">
                <div className="text-[28px] font-mono text-text-strong leading-[1.5]">
                    ABCDEFGHIJKLMNOPQRSTUVWXYZ
                    <br />
                    abcdefghijklmnopqrstuvwxyz
                    <br />
                    0123456789 !@#$%^&amp;*()
                </div>
            </Section>
        </div>
    )
};
