export const {
  ACCOUNT_ID,
  AUTHORIZATION_SESSION_TABLE,
  AUTH_CALLBACK_URL,
  AUTH_VHOST,
  AWS_REGION,
  COOKIE_SECRET,
  DASHBOARD_API,
  DASHBOARD_API_ACCESS_TOKEN,
  DYNAMODB_AWS_REGION,
  FUNCTIONS_AWS_REGION,
  GLOBAL_FUNCTION_PROXY_HASH,
  HIT_NOTIFIER_LAMBDA_NAME,
  IGNORED_BUGSNAG_EXCEPTIONS = '',
  INTEGRATION_EXTERNAL_API_COUNT_TABLE_NAME,
  INTEGRATION_PLANS_TABLE_NAME,
  ORGANIZATION_EXTERNAL_API_COUNT_TABLE_NAME,
  PROXY_VHOST,
  REDIS_HOST,
  REDIS_PORT,
  STAGE,
  SQS_AGENT_ACTIVE_DATA_COLLECTION_QUEUE_NAME
} = process.env as {
  ACCOUNT_ID: string
  AUTHORIZATION_SESSION_TABLE: string
  AUTH_CALLBACK_URL: string
  AUTH_VHOST: string
  AWS_REGION: string
  COOKIE_SECRET: string
  DASHBOARD_API: string
  DASHBOARD_API_ACCESS_TOKEN: string
  DYNAMODB_AWS_REGION: string
  FUNCTIONS_AWS_REGION: string
  GLOBAL_FUNCTION_PROXY_HASH: string
  HIT_NOTIFIER_LAMBDA_NAME: string
  IGNORED_BUGSNAG_EXCEPTIONS: string
  INTEGRATION_EXTERNAL_API_COUNT_TABLE_NAME: string
  INTEGRATION_PLANS_TABLE_NAME: string
  ORGANIZATION_EXTERNAL_API_COUNT_TABLE_NAME: string
  PROXY_VHOST: string
  REDIS_HOST: string
  REDIS_PORT: string
  STAGE: string
  SQS_AGENT_ACTIVE_DATA_COLLECTION_QUEUE_NAME: string
}

export const LOCAL_CLI_HOST_URL = 'http://127.0.0.1:45677'
