#!/usr/bin/env sh
set -e

. "$(dirname -- "$0")/_/husky.sh"

npx lint-staged --allow-empty

diff=$(git diff --cached --numstat)
if [ $(echo "$diff" | grep -c "./docs-v2/integrations/all/" | grep -c "./packages/shared/flows.yaml") -gt "0" ]; then
    npm run docs:generate
    git add ./docs-v2/snippets/generated/
fi

if [ $(echo "$diff" | grep -c "./packages/api-public/") -gt "0" ]; then
    npm run openapi:generate -w @nangohq/api-public
    git add ./packages/api-public/openapi.json
fi
