import type { Meta, StoryObj } from '@storybook/react';

const meta: Meta = {
    title: 'Design System/Tokens/Typography',
    parameters: {
        layout: 'padded'
    }
};

export default meta;

// ─── Helpers ────────────────────────────────────────────────────────────────

interface TypeEntry {
    /** CSS class generated by tokens pipeline, e.g. 'type-heading-lg' */
    className: string;
    /** Token path label, e.g. 'heading / lg' */
    name: string;
    /** Short usage description */
    description: string;
    /** True for mono tokens — renders code sample instead of prose */
    mono?: boolean;
}

const HEADING: TypeEntry[] = [
    { className: 'type-heading-lg', name: 'heading / lg', description: 'page headings, hero titles' },
    { className: 'type-heading-md', name: 'heading / md', description: 'section headings' },
    { className: 'type-heading-sm', name: 'heading / sm', description: 'sub-section headings' }
];

const TEXT_REGULAR: TypeEntry[] = [
    { className: 'type-text-regular-md', name: 'text / regular / md', description: 'standard body text' },
    { className: 'type-text-regular-sm', name: 'text / regular / sm', description: 'dense body / tables' },
    { className: 'type-text-regular-xs', name: 'text / regular / xs', description: 'small body / captions' }
];

const TEXT_MEDIUM: TypeEntry[] = [
    { className: 'type-text-medium-md', name: 'text / medium / md', description: 'emphasized body text' },
    { className: 'type-text-medium-sm', name: 'text / medium / sm', description: 'emphasized dense body' },
    { className: 'type-text-medium-xs', name: 'text / medium / xs', description: 'emphasized small body' }
];

const LABEL: TypeEntry[] = [
    { className: 'type-label-lg', name: 'label / lg', description: 'form labels, prominent chips' },
    { className: 'type-label-md', name: 'label / md', description: 'badges, table headers' },
    { className: 'type-label-sm', name: 'label / sm', description: 'metadata, helper text' },
    { className: 'type-label-xs', name: 'label / xs', description: 'tag content, inline status' },
    { className: 'type-label-xxs', name: 'label / xxs', description: 'finest micro labels — use sparingly' }
];

const CODE_REGULAR: TypeEntry[] = [
    { className: 'type-code-regular-sm', name: 'code / regular / sm', description: 'inline code, IDs, slugs', mono: true },
    { className: 'type-code-regular-xs', name: 'code / regular / xs', description: 'small inline code', mono: true },
    { className: 'type-code-regular-xxs', name: 'code / regular / xxs', description: 'finest mono', mono: true }
];

const CODE_MEDIUM: TypeEntry[] = [
    { className: 'type-code-medium-md', name: 'code / medium / md', description: 'emphasized code', mono: true },
    { className: 'type-code-medium-sm', name: 'code / medium / sm', description: 'emphasized inline code', mono: true },
    { className: 'type-code-medium-xs', name: 'code / medium / xs', description: 'emphasized small inline code', mono: true },
    { className: 'type-code-medium-xxs', name: 'code / medium / xxs', description: 'emphasized finest mono', mono: true }
];

const SAMPLE_TEXT = 'The quick brown fox jumps over the lazy dog';
const SAMPLE_MONO = 'const api_key = "nango_live_abc123xyz";';

function TypeRow({ entry }: { entry: TypeEntry }) {
    return (
        <div className="grid grid-cols-[260px_1fr] gap-4 items-baseline py-3 border-b border-border-default">
            <div className="text-[11px] font-mono pt-0.5">
                <div className="font-medium text-text-secondary">{entry.name}</div>
                <div className="mt-1 font-normal text-text-muted">{entry.description}</div>
            </div>
            <div className={`text-text-strong ${entry.className}`}>{entry.mono ? SAMPLE_MONO : SAMPLE_TEXT}</div>
        </div>
    );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
    return (
        <div className="mb-12">
            <h2 className="story-section-heading mb-3">{title}</h2>
            {children}
        </div>
    );
}

// ─── Stories ────────────────────────────────────────────────────────────────

type Story = StoryObj<typeof meta>;

export const TypeScale: Story = {
    name: 'Type Scale',
    render: () => (
        <div className="p-8">
            <Section title="Geist Sans — Heading">
                {HEADING.map((e) => (
                    <TypeRow key={e.className} entry={e} />
                ))}
            </Section>

            <Section title="Geist Sans — Text · Regular">
                {TEXT_REGULAR.map((e) => (
                    <TypeRow key={e.className} entry={e} />
                ))}
            </Section>

            <Section title="Geist Sans — Text · Medium">
                {TEXT_MEDIUM.map((e) => (
                    <TypeRow key={e.className} entry={e} />
                ))}
            </Section>

            <Section title="Geist Sans — Label">
                {LABEL.map((e) => (
                    <TypeRow key={e.className} entry={e} />
                ))}
            </Section>

            <Section title="Geist Mono — Code · Regular">
                {CODE_REGULAR.map((e) => (
                    <TypeRow key={e.className} entry={e} />
                ))}
            </Section>

            <Section title="Geist Mono — Code · Medium">
                {CODE_MEDIUM.map((e) => (
                    <TypeRow key={e.className} entry={e} />
                ))}
            </Section>
        </div>
    )
};

export const FontFamilies: Story = {
    name: 'Font Families',
    render: () => (
        <div className="max-w-[700px] p-8">
            <Section title="Geist Sans — UI text">
                <div className="text-[28px] font-sans text-text-strong leading-[1.5]">
                    ABCDEFGHIJKLMNOPQRSTUVWXYZ
                    <br />
                    abcdefghijklmnopqrstuvwxyz
                    <br />
                    0123456789 !@#$%^&amp;*()
                </div>
            </Section>
            <Section title="Geist Mono — Code, IDs, API keys">
                <div className="text-[28px] font-mono text-text-strong leading-[1.5]">
                    ABCDEFGHIJKLMNOPQRSTUVWXYZ
                    <br />
                    abcdefghijklmnopqrstuvwxyz
                    <br />
                    0123456789 !@#$%^&amp;*()
                </div>
            </Section>
        </div>
    )
};
